on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Installs CLI on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: which inngest
      - run: inngest version
