on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Installs CLI on ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: Test that Git Bash also works on Windows
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - id: action
        uses: ./

        # Show the installed location
      - if: matrix.os != 'windows-latest'
        run: which inngest
        shell: bash
      - if: matrix.os == 'windows-latest'
        run: where inngest
        shell: cmd

        # Ensure the CLI works by calling `inngest version`
      - if: matrix.os != 'windows-latest'
        run: inngest version
        shell: bash
      - if: matrix.os == 'windows-latest'
        run: inngest version
        shell: cmd

        # Ensure the step output was given
      - run: echo ${{ steps.action.outputs.version }}
