on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Installs CLI on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: action
        uses: ./
      - run: which inngest
        if: ${{ matrix.os }} != 'windows-latest'
      - run: where inngest
        if: ${{ matrix.os }} == 'windows-latest'
      - run: inngest version
        shell: bash
        if: ${{ matrix.os }} != 'windows-latest'
      - run: echo ${{ steps.action.outputs.version }}
        shell: cmd
        if: ${{ matrix.os }} == 'windows-latest'
